/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csii.taller1;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus PC
 */
public class Puntos extends javax.swing.JFrame {

    int[] vectorNumerico1PrimerPunto;
    int[] vectorNumerico2PrimerPunto;
    int[][] matriznumericatercerpunto;
    Estudiante Primero;
    Estudiante[] ListaE;
    int NEstudiantes;

    /**
     * Creates new form Puntos
     */
    public Puntos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVector1PrimerPunto = new javax.swing.JTextField();
        txtVector2PrimerPunto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botonComparaPrimerPunto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalidaV1PrimerPunto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSalidaV2PrimerPunto = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSalidaV3PrimerPunto = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEntradaSegundoPunto = new javax.swing.JTextField();
        botonMediaSegundoPunto = new javax.swing.JButton();
        botonMedianaSegundoPunto = new javax.swing.JButton();
        botonModaSegundoPunto = new javax.swing.JButton();
        botonVarianzaSegundoPunto = new javax.swing.JButton();
        botonDesviacionSegundoPunto = new javax.swing.JButton();
        botonCuartilSegundoPunto = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSalidaSegundoPunto = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtEntradaTercerPunto = new javax.swing.JTextArea();
        botonLeerTercerPunto = new javax.swing.JButton();
        botonCTercerPunto = new javax.swing.JButton();
        botonATercerPunto = new javax.swing.JButton();
        botonTTercerPunto = new javax.swing.JButton();
        botonXTercerPunto = new javax.swing.JButton();
        botonOTercerPunto = new javax.swing.JButton();
        botonUTercerPunto = new javax.swing.JButton();
        botonITercerPunto = new javax.swing.JButton();
        botonZTercerPunto = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtSalidaTercerPunto = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNumEstudiantesCuartoPunto = new javax.swing.JTextField();
        botonCantidadEstudiantesCuartopunto = new javax.swing.JButton();
        txtCodigoCuartoPunto = new javax.swing.JTextField();
        txtNombreCuartoPunto = new javax.swing.JTextField();
        txtEdadCuartoPunto = new javax.swing.JTextField();
        txtSemestreCuartoPunto = new javax.swing.JTextField();
        txtPromedioCuartoPunto = new javax.swing.JTextField();
        botonIngresarEstudianteCuartoPunto = new javax.swing.JButton();
        botonProcesarCuartoPunto = new javax.swing.JButton();
        botonEstudianteMayorPromedioCuartoPunto = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtSalidaCuartoPunto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Vector1:");

        jLabel2.setText("Vector2:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Favor ingresar los vectores deben estar separados por espacios.");

        botonComparaPrimerPunto.setText("Comparar");
        botonComparaPrimerPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonComparaPrimerPuntoMouseClicked(evt);
            }
        });

        txtSalidaV1PrimerPunto.setColumns(20);
        txtSalidaV1PrimerPunto.setRows(5);
        jScrollPane1.setViewportView(txtSalidaV1PrimerPunto);

        txtSalidaV2PrimerPunto.setColumns(20);
        txtSalidaV2PrimerPunto.setRows(5);
        jScrollPane2.setViewportView(txtSalidaV2PrimerPunto);

        txtSalidaV3PrimerPunto.setColumns(20);
        txtSalidaV3PrimerPunto.setRows(5);
        jScrollPane3.setViewportView(txtSalidaV3PrimerPunto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtVector1PrimerPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtVector2PrimerPunto)))
                                .addGap(18, 18, 18)
                                .addComponent(botonComparaPrimerPunto))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtVector1PrimerPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtVector2PrimerPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(botonComparaPrimerPunto)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Primer Punto", jPanel1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Favor ingresar el vector separado por comas.");

        jLabel5.setText("Vector:");

        botonMediaSegundoPunto.setText("Media");
        botonMediaSegundoPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMediaSegundoPuntoMouseClicked(evt);
            }
        });

        botonMedianaSegundoPunto.setText("Mediana");
        botonMedianaSegundoPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMedianaSegundoPuntoMouseClicked(evt);
            }
        });

        botonModaSegundoPunto.setText("Moda");
        botonModaSegundoPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonModaSegundoPuntoMouseClicked(evt);
            }
        });

        botonVarianzaSegundoPunto.setText("Varianza");
        botonVarianzaSegundoPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVarianzaSegundoPuntoMouseClicked(evt);
            }
        });

        botonDesviacionSegundoPunto.setText("Desviación Estandar");
        botonDesviacionSegundoPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDesviacionSegundoPuntoMouseClicked(evt);
            }
        });

        botonCuartilSegundoPunto.setText("Cuartil 2");
        botonCuartilSegundoPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCuartilSegundoPuntoMouseClicked(evt);
            }
        });

        txtSalidaSegundoPunto.setColumns(20);
        txtSalidaSegundoPunto.setRows(5);
        jScrollPane4.setViewportView(txtSalidaSegundoPunto);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonMediaSegundoPunto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonMedianaSegundoPunto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonModaSegundoPunto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonVarianzaSegundoPunto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonDesviacionSegundoPunto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCuartilSegundoPunto))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEntradaSegundoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEntradaSegundoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMediaSegundoPunto)
                    .addComponent(botonMedianaSegundoPunto)
                    .addComponent(botonModaSegundoPunto)
                    .addComponent(botonVarianzaSegundoPunto)
                    .addComponent(botonDesviacionSegundoPunto)
                    .addComponent(botonCuartilSegundoPunto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Segundo Punto", jPanel2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Favor separar las columas por espacios y las filas por saltos de linea.");

        txtEntradaTercerPunto.setColumns(20);
        txtEntradaTercerPunto.setRows(5);
        jScrollPane5.setViewportView(txtEntradaTercerPunto);

        botonLeerTercerPunto.setText("Leer Matriz");
        botonLeerTercerPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLeerTercerPuntoMouseClicked(evt);
            }
        });

        botonCTercerPunto.setText("Matriz en C");
        botonCTercerPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCTercerPuntoMouseClicked(evt);
            }
        });

        botonATercerPunto.setText("Matriz en A");
        botonATercerPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonATercerPuntoMouseClicked(evt);
            }
        });

        botonTTercerPunto.setText("Matriz en T");
        botonTTercerPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonTTercerPuntoMouseClicked(evt);
            }
        });

        botonXTercerPunto.setText("Matriz en X");
        botonXTercerPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonXTercerPuntoMouseClicked(evt);
            }
        });

        botonOTercerPunto.setText("Matriz en O");
        botonOTercerPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonOTercerPuntoMouseClicked(evt);
            }
        });

        botonUTercerPunto.setText("Matriz en U");
        botonUTercerPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonUTercerPuntoMouseClicked(evt);
            }
        });

        botonITercerPunto.setText("Matriz en I");
        botonITercerPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonITercerPuntoMouseClicked(evt);
            }
        });

        botonZTercerPunto.setText("Matriz en Z");
        botonZTercerPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonZTercerPuntoMouseClicked(evt);
            }
        });

        txtSalidaTercerPunto.setColumns(20);
        txtSalidaTercerPunto.setRows(5);
        jScrollPane6.setViewportView(txtSalidaTercerPunto);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(botonLeerTercerPunto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCTercerPunto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonATercerPunto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonTTercerPunto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonXTercerPunto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonOTercerPunto)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(botonUTercerPunto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonITercerPunto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonZTercerPunto)
                                .addGap(137, 137, 137))))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(76, 76, 76))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLeerTercerPunto)
                    .addComponent(botonCTercerPunto)
                    .addComponent(botonATercerPunto)
                    .addComponent(botonTTercerPunto)
                    .addComponent(botonXTercerPunto)
                    .addComponent(botonOTercerPunto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonITercerPunto)
                    .addComponent(botonZTercerPunto)
                    .addComponent(botonUTercerPunto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tercer Punto", jPanel3);

        jLabel7.setText("Numero de estudiantes:");

        jLabel8.setText("Codigo:");

        jLabel9.setText("Nombre:");

        jLabel10.setText("Edad:");

        jLabel11.setText("Semestre:");

        jLabel12.setText("Promedio:");

        botonCantidadEstudiantesCuartopunto.setText("Definir cantidad de estudiantes");
        botonCantidadEstudiantesCuartopunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCantidadEstudiantesCuartopuntoMouseClicked(evt);
            }
        });

        botonIngresarEstudianteCuartoPunto.setText("Ingreasar estudiante");
        botonIngresarEstudianteCuartoPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIngresarEstudianteCuartoPuntoMouseClicked(evt);
            }
        });

        botonProcesarCuartoPunto.setText("Procesar datos");
        botonProcesarCuartoPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonProcesarCuartoPuntoMouseClicked(evt);
            }
        });

        botonEstudianteMayorPromedioCuartoPunto.setText("Estudiante con mayor promedio");
        botonEstudianteMayorPromedioCuartoPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEstudianteMayorPromedioCuartoPuntoMouseClicked(evt);
            }
        });

        txtSalidaCuartoPunto.setColumns(20);
        txtSalidaCuartoPunto.setRows(5);
        jScrollPane7.setViewportView(txtSalidaCuartoPunto);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSemestreCuartoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPromedioCuartoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(botonIngresarEstudianteCuartoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonProcesarCuartoPunto)
                        .addGap(18, 18, 18)
                        .addComponent(botonEstudianteMayorPromedioCuartoPunto))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumEstudiantesCuartoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCantidadEstudiantesCuartopunto))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoCuartoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreCuartoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEdadCuartoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNumEstudiantesCuartoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCantidadEstudiantesCuartopunto))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCodigoCuartoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombreCuartoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtEdadCuartoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSemestreCuartoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtPromedioCuartoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonIngresarEstudianteCuartoPunto)
                    .addComponent(botonProcesarCuartoPunto)
                    .addComponent(botonEstudianteMayorPromedioCuartoPunto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cuarto Punto", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonComparaPrimerPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComparaPrimerPuntoMouseClicked
        String cadenaInicial = txtVector1PrimerPunto.getText();
        String[] vectorString = cadenaInicial.split(" ");
        vectorNumerico1PrimerPunto = new int[vectorString.length];

        for (int i = 0; i < vectorNumerico1PrimerPunto.length; i++) {
            vectorNumerico1PrimerPunto[i] = Integer.parseInt(vectorString[i]);
        }

        for (int i = 0; i < vectorNumerico1PrimerPunto.length - 1; i++) {
            for (int j = 0; j < vectorNumerico1PrimerPunto.length - 1; j++) {
                if (vectorNumerico1PrimerPunto[j] > vectorNumerico1PrimerPunto[j + 1]) {
                    int aux = 0;
                    aux = vectorNumerico1PrimerPunto[j];
                    vectorNumerico1PrimerPunto[j] = vectorNumerico1PrimerPunto[j + 1];
                    vectorNumerico1PrimerPunto[j + 1] = aux;
                }
            }
        }
        txtSalidaV1PrimerPunto.setText("el vector es " + cadenaInicial +
                "\n el vector ordenado es: ");
        
        for (int i = 0; i < vectorNumerico1PrimerPunto.length; i++) {
            txtSalidaV1PrimerPunto.setText(txtSalidaV1PrimerPunto.getText() +
                    vectorNumerico1PrimerPunto[i] + ",");
        }

        String cadenaIni = txtVector2PrimerPunto.getText();
        String[] vectorStrin = cadenaIni.split(" ");
        vectorNumerico2PrimerPunto = new int[vectorStrin.length];

        for (int i = 0; i < vectorNumerico2PrimerPunto.length; i++) {
            vectorNumerico2PrimerPunto[i] = Integer.parseInt(vectorStrin[i]);
        }
        
        
        
        for (int i = 0; i < vectorNumerico2PrimerPunto.length - 1; i++) {
            for (int j = 0; j < vectorNumerico2PrimerPunto.length - 1; j++) {
                if (vectorNumerico2PrimerPunto[j] > vectorNumerico2PrimerPunto[j + 1]) {
                    
                    int aux = 0;
                    aux = vectorNumerico2PrimerPunto[j];
                    vectorNumerico2PrimerPunto[j] = vectorNumerico2PrimerPunto[j + 1];
                    vectorNumerico2PrimerPunto[j + 1] = aux;
                }
            }
        }
        
        txtSalidaV2PrimerPunto.setText("el vector es " + cadenaIni + "\n el vector ordenado es: ");
        
        for (int i = 0; i < vectorNumerico2PrimerPunto.length; i++) {
            txtSalidaV2PrimerPunto.setText(txtSalidaV2PrimerPunto.getText() +
                    vectorNumerico2PrimerPunto[i] + ",");
        }
        System.out.println("\n");
        
        int espacio = 0;
        
        for (int i = 0; i < vectorNumerico1PrimerPunto.length; i++) {
            for (int j = 0; j < vectorNumerico2PrimerPunto.length; j++) {
                if (vectorNumerico1PrimerPunto[i] == vectorNumerico2PrimerPunto[j]) {
                    espacio = espacio + 1;
                }
            }
        }
        
        int[] vector3 = new int[espacio];
        int k = 0;
        
        for (int i = 0; i < vectorNumerico1PrimerPunto.length; i++) {
            for (int j = 0; j < vectorNumerico2PrimerPunto.length; j++) {
                if (vectorNumerico1PrimerPunto[i] == vectorNumerico2PrimerPunto[j]) {
                    vector3[k] = vectorNumerico1PrimerPunto[i];
                    k++;
                }
            }
        }
        
        txtSalidaV3PrimerPunto.setText("Los elementos iguales son: ");
        
        for (int i = 0; i < vector3.length; i++) {
            txtSalidaV3PrimerPunto.setText(txtSalidaV3PrimerPunto.getText() + vector3[i] + "  ");
        }
    }//GEN-LAST:event_botonComparaPrimerPuntoMouseClicked

    private void botonMediaSegundoPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMediaSegundoPuntoMouseClicked
        String cadenaInicial = txtEntradaSegundoPunto.getText();
        String[] vectorString = cadenaInicial.split(",");

        float[] vectorNumeros = new float[(vectorString.length)];

        for (int i = 0; i < vectorNumeros.length; i++) {
            vectorNumeros[i] = Float.parseFloat(vectorString[i]);
        }

        float suma = 0;

        for (int i = 0; i < vectorNumeros.length; i++) {
            suma = suma + vectorNumeros[i];
        }

        double media = 0;
        media = suma / vectorNumeros.length;

        txtSalidaSegundoPunto.setText("La media es: " + Double.toString(media));
    }//GEN-LAST:event_botonMediaSegundoPuntoMouseClicked

    private void botonMedianaSegundoPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMedianaSegundoPuntoMouseClicked
        String cadenaInicial = txtEntradaSegundoPunto.getText();
        String[] vectorString = cadenaInicial.split(",");

        int[] vectorNumeros = new int[(vectorString.length)];

        for (int i = 0; i < vectorNumeros.length; i++) {
            vectorNumeros[i] = Integer.parseInt(vectorString[i]);
        }
        
        for (int i = 0; i < vectorNumeros.length - 1; i++) {
            for (int j = 0; j < vectorNumeros.length - 1; j++) {
                if (vectorNumeros[j] > vectorNumeros[j + 1]) {
                    int aux = 0;
                    aux = vectorNumeros[j];
                    vectorNumeros[j] = vectorNumeros[j + 1];
                    vectorNumeros[j + 1] = aux;
                }
            }
        }

        double mediana;

        if (vectorNumeros.length % 2 == 0) {
            int sumaMedios = vectorNumeros[vectorNumeros.length / 2]
                    + vectorNumeros[vectorNumeros.length / 2 - 1];
            mediana = (double) sumaMedios / 2;
        } else {
            mediana = vectorNumeros[vectorNumeros.length / 2];
        }
        txtSalidaSegundoPunto.setText("La mediana es: " + Double.toString(mediana));
    }//GEN-LAST:event_botonMedianaSegundoPuntoMouseClicked

    private void botonModaSegundoPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonModaSegundoPuntoMouseClicked
        String cadenaInicial = txtEntradaSegundoPunto.getText();
        String[] vectorString = cadenaInicial.split(",");

        double[] vectorNumeros = new double[(vectorString.length)];
        
        for (int k = 0; k < vectorNumeros.length; k++) {
            vectorNumeros[k] = Double.parseDouble(vectorString[k]);
        }

        int maxRep = 0;
        double moda = 0;

        for (int i = 0; i < vectorNumeros.length; i++) {
            int numRep = 0;
            for (int j = 0; j < vectorNumeros.length; j++) {
                if (vectorNumeros[i] == vectorNumeros[j]) {
                    numRep++;
                }
                if (numRep > maxRep) {
                    moda = vectorNumeros[i];
                    maxRep = numRep;
                }
            }
        }
        txtSalidaSegundoPunto.setText(moda + " se repitio " + maxRep);
    }//GEN-LAST:event_botonModaSegundoPuntoMouseClicked

    private void botonVarianzaSegundoPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVarianzaSegundoPuntoMouseClicked
        String cadenaInicial = txtEntradaSegundoPunto.getText();
        String[] vectorString = cadenaInicial.split(",");

        int[] vectorNumeros = new int[(vectorString.length)];
        double[] vectorNum = new double[(vectorString.length)];

        for (int i = 0; i < vectorNumeros.length; i++) {
            vectorNumeros[i] = Integer.parseInt(vectorString[i]);
        }

        int suma = 0;
        double promedio = 0d;

        for (int i = 0; i < vectorNumeros.length; i++) {
            suma = suma + vectorNumeros[i];
            promedio = (suma) / vectorNumeros.length;
        }
        for (int j = 0; j < vectorNum.length; j++) {
            vectorNum[j] = vectorNumeros[j] - promedio;
        }

        double zuma = 0;
        double pronedio = 0d;

        for (int j = 0; j < vectorNum.length; j++) {
            zuma = zuma + Math.pow(vectorNum[j], 2);
            pronedio = zuma / vectorNum.length;
        }
        txtSalidaSegundoPunto.setText("La varianza es: " + Double.toString(pronedio));
    }//GEN-LAST:event_botonVarianzaSegundoPuntoMouseClicked

    private void botonDesviacionSegundoPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDesviacionSegundoPuntoMouseClicked
        String cadenaInicial = txtEntradaSegundoPunto.getText();
        String[] vectorString = cadenaInicial.split(",");
        double raiz = 0;

        int[] vectorNumeros = new int[(vectorString.length)];
        double[] vectorNum = new double[(vectorString.length)];

        for (int i = 0; i < vectorNumeros.length; i++) {
            vectorNumeros[i] = Integer.parseInt(vectorString[i]);
        }

        int suma = 0;
        double promedio = 0;

        for (int i = 0; i < vectorNumeros.length; i++) {
            suma = suma + vectorNumeros[i];
            promedio = (suma) / vectorNumeros.length;
        }
        for (int j = 0; j < vectorNum.length; j++) {
            vectorNum[j] = vectorNumeros[j] - promedio;
        }

        double zuma = 0;
        double pronedio = 0;

        for (int j = 0; j < vectorNum.length; j++) {
            zuma = zuma + Math.pow(vectorNum[j], 2);
            pronedio = zuma / vectorNum.length;
        }
        raiz = Math.sqrt(pronedio);
        txtSalidaSegundoPunto.setText("La desviación es: " + Double.toString(raiz));
    }//GEN-LAST:event_botonDesviacionSegundoPuntoMouseClicked

    private void botonCuartilSegundoPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCuartilSegundoPuntoMouseClicked
        String cadenaInicial = txtEntradaSegundoPunto.getText();
        String[] vectorString = cadenaInicial.split(",");

        int[] vectorNumeros = new int[(vectorString.length)];

        for (int i = 0; i < vectorNumeros.length; i++) {
            vectorNumeros[i] = Integer.parseInt(vectorString[i]);
        }
        for (int i = 0; i < vectorNumeros.length - 1; i++) {
            for (int j = 0; j < vectorNumeros.length - 1; j++) {
                if (vectorNumeros[j] > vectorNumeros[j + 1]) {
                    int aux = 0;
                    aux = vectorNumeros[j];
                    vectorNumeros[j] = vectorNumeros[j + 1];
                    vectorNumeros[j + 1] = aux;
                }
            }
        }

        double cuartil2;

        if (vectorNumeros.length % 2 == 0) {
            int sumaMedios = vectorNumeros[vectorNumeros.length / 2]
                    + vectorNumeros[vectorNumeros.length / 2 - 1];
            cuartil2 = (double) sumaMedios / 2;
        } else {
            cuartil2 = vectorNumeros[vectorNumeros.length / 2];
        }
        txtSalidaSegundoPunto.setText("El cuartil 2 es: " + Double.toString(cuartil2));
    }//GEN-LAST:event_botonCuartilSegundoPuntoMouseClicked

    private void botonLeerTercerPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLeerTercerPuntoMouseClicked
        String matriz = txtEntradaTercerPunto.getText();
        String[] filasString = matriz.split("\n");
        matriznumericatercerpunto = new int[filasString.length][filasString.length];

        for (int i = 0; i < filasString.length; i++) {
            String fila = filasString[i];
            String[] numerosString = fila.split(" ");
            for (int j = 0; j < numerosString.length; j++) {
                String numS = numerosString[j].trim();//para descartar espacios que el usuario meta por error
                int num = Integer.parseInt(numS);
                matriznumericatercerpunto[i][j] = num;
            }
        }
        txtSalidaTercerPunto.setText(matriz);
               
    }//GEN-LAST:event_botonLeerTercerPuntoMouseClicked

    private void botonCTercerPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCTercerPuntoMouseClicked
        txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText()
                + "\n\nRecorrido en C es: \n\n");

        for (int i = 0; i < matriznumericatercerpunto.length; i++) {
            for (int j = 0; j < matriznumericatercerpunto[i].length; j++) {
                if (i == 0 || j == 0 || i == matriznumericatercerpunto.length - 1) {
                    txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText()
                            + matriznumericatercerpunto[i][j] + " ");
                } else {
                    txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() + "   ");
                }
            }
            txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() + "\n");
        }
    }//GEN-LAST:event_botonCTercerPuntoMouseClicked

    private void botonATercerPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonATercerPuntoMouseClicked
        txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText()
                + "\n\nRecorrido en A es: \n\n");

        for (int i = 0; i < matriznumericatercerpunto.length; i++) {
            for (int j = 0; j < matriznumericatercerpunto[i].length; j++) {
                if (i == 0 || j == matriznumericatercerpunto.length - 1 || j == 0 ||
                        i == matriznumericatercerpunto.length/2) {
                    txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText()
                            + matriznumericatercerpunto[i][j] + " ");
                } else {
                    txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() + "   ");
                }
            }
            txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() + "\n");
        }
    }//GEN-LAST:event_botonATercerPuntoMouseClicked

    private void botonTTercerPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTTercerPuntoMouseClicked
        txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText()
                + "\n\nRecorrido en T es: \n\n");

        for (int i = 0; i < matriznumericatercerpunto.length; i++) {
            for (int j = 0; j < matriznumericatercerpunto[i].length; j++) {
                if (i == 0 || j == matriznumericatercerpunto[j].length / 2) {
                    txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText()
                            + matriznumericatercerpunto[i][j] + " ");
                } else {
                    txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() + "   ");
                }
            }
            txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() + "\n");
        }
    }//GEN-LAST:event_botonTTercerPuntoMouseClicked

    private void botonXTercerPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonXTercerPuntoMouseClicked
        txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText()
                + "\n\nRecorrido en X es: \n\n");

        for (int i = 0; i < matriznumericatercerpunto.length; i++) {
            for (int j = 0; j < matriznumericatercerpunto[i].length; j++) {
                if (i == j || i + j == matriznumericatercerpunto.length-1) {
                    txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() 
                            + matriznumericatercerpunto[i][j] + " ");
                } else {
                    txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() 
                            + "     ");
                }
            }
            txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() + "\n");
        }
        
    }//GEN-LAST:event_botonXTercerPuntoMouseClicked

    private void botonOTercerPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOTercerPuntoMouseClicked
        txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText()
                + "\n\nRecorrido en O es: \n\n");

        for (int i = 0; i < matriznumericatercerpunto.length; i++) {
            for (int j = 0; j < matriznumericatercerpunto[i].length; j++) {
                if (i == 0 || j == matriznumericatercerpunto.length - 1 ||
                        i == matriznumericatercerpunto.length - 1 || j == 0) {
                    txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText()
                            + matriznumericatercerpunto[i][j] + " ");
                } else {
                    txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() 
                            + "   ");
                }
            }
            txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() + "\n");
        }
    }//GEN-LAST:event_botonOTercerPuntoMouseClicked

    private void botonUTercerPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonUTercerPuntoMouseClicked
        txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText()
                + "\n\nRecorrido en U es: \n\n");

        for (int i = 0; i < matriznumericatercerpunto.length; i++) {
            for (int j = 0; j < matriznumericatercerpunto[i].length; j++) {
                if (i == matriznumericatercerpunto.length - 1 || j == 0 ||
                        j == matriznumericatercerpunto.length - 1) {
                    txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText()
                            + matriznumericatercerpunto[i][j] + " ");
                } else {
                    txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() 
                            + "   ");
                }
            }
            txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() + "\n");
        }
    }//GEN-LAST:event_botonUTercerPuntoMouseClicked

    private void botonITercerPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonITercerPuntoMouseClicked
        txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText()
                + "\n\nRecorrido en U es: \n\n");

        for (int i = 0; i < matriznumericatercerpunto.length; i++) {
            for (int j = 0; j < matriznumericatercerpunto[i].length; j++) {
                if (i == 0 || j == matriznumericatercerpunto.length / 2 ||
                        i == matriznumericatercerpunto.length - 1) {
                    txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText()
                            + matriznumericatercerpunto[i][j] + " ");
                } else {
                    txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() 
                            + "   ");
                }
            }
            txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() + "\n");
        }
    }//GEN-LAST:event_botonITercerPuntoMouseClicked

    private void botonZTercerPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonZTercerPuntoMouseClicked
        txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText()
                + "\n\nRecorrido en Z es: \n\n");

        for (int i = 0; i < matriznumericatercerpunto.length; i++) {
            for (int j = 0; j < matriznumericatercerpunto[i].length; j++) {
                if (i == 0 || i == matriznumericatercerpunto.length - 1 || 
                        i + j == matriznumericatercerpunto.length-1) {
                    txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText()
                            + matriznumericatercerpunto[i][j] + " ");
                } else {
                    txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() 
                            + "     ");
                }
            }
            txtSalidaTercerPunto.setText(txtSalidaTercerPunto.getText() + "\n");
        }
    }//GEN-LAST:event_botonZTercerPuntoMouseClicked

    private void botonCantidadEstudiantesCuartopuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCantidadEstudiantesCuartopuntoMouseClicked
        ListaE = new Estudiante[Integer.parseInt(txtNumEstudiantesCuartoPunto.getText())];
        NEstudiantes = 0;
        JOptionPane.showMessageDialog(rootPane, "Lista de estudiantes ingresada correctamente");
    }//GEN-LAST:event_botonCantidadEstudiantesCuartopuntoMouseClicked

    private void botonIngresarEstudianteCuartoPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresarEstudianteCuartoPuntoMouseClicked
        int codigo = Integer.parseInt(txtCodigoCuartoPunto.getText());
        String nombre = txtNombreCuartoPunto.getText();
        int edad = Integer.parseInt(txtEdadCuartoPunto.getText());
        int semestre = Integer.parseInt(txtSemestreCuartoPunto.getText());
        double promedio = Double.parseDouble(txtPromedioCuartoPunto.getText());

        Primero = new Estudiante(codigo, nombre, edad, semestre, promedio);

        ListaE[NEstudiantes] = Primero;
        NEstudiantes++;

        txtSalidaCuartoPunto.setText(txtSalidaCuartoPunto.getText()
                + "\nEstudiante Ingresado Correctamente:\n" + Primero.toString());
    }//GEN-LAST:event_botonIngresarEstudianteCuartoPuntoMouseClicked

    private void botonProcesarCuartoPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProcesarCuartoPuntoMouseClicked
        
        for (int K = 0; K < ListaE.length; K++) {

            int semestresF = ListaE[K].calcularSemestresFaltantes();
            double edadG = ListaE[K].calcularedadgraduacion();

            txtSalidaCuartoPunto.setText(txtSalidaCuartoPunto.getText()
                    + "\nAl estudiante " + ListaE[K].getNombre()
                    + " le faltan " + Integer.toString(semestresF)
                    + " semestres para graduarse" + "\nY se graduara a los "
                    + Double.toString(edadG) + " años de edad\n");
        }
    }//GEN-LAST:event_botonProcesarCuartoPuntoMouseClicked

    private void botonEstudianteMayorPromedioCuartoPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEstudianteMayorPromedioCuartoPuntoMouseClicked
        if (ListaE != null && ListaE.length > 0) {
            Estudiante Mpromedio = Estudiante.mejorPromedio(ListaE);
            txtSalidaCuartoPunto.setText("El estudiante con mayor promedio es: \n"
                    + Mpromedio.getNombre() + " con el codigo: " + Mpromedio.getCodigo()
                    + ", y su promedio es: " + Mpromedio.getPromedio());
        }
    }//GEN-LAST:event_botonEstudianteMayorPromedioCuartoPuntoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puntos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonATercerPunto;
    private javax.swing.JButton botonCTercerPunto;
    private javax.swing.JButton botonCantidadEstudiantesCuartopunto;
    private javax.swing.JButton botonComparaPrimerPunto;
    private javax.swing.JButton botonCuartilSegundoPunto;
    private javax.swing.JButton botonDesviacionSegundoPunto;
    private javax.swing.JButton botonEstudianteMayorPromedioCuartoPunto;
    private javax.swing.JButton botonITercerPunto;
    private javax.swing.JButton botonIngresarEstudianteCuartoPunto;
    private javax.swing.JButton botonLeerTercerPunto;
    private javax.swing.JButton botonMediaSegundoPunto;
    private javax.swing.JButton botonMedianaSegundoPunto;
    private javax.swing.JButton botonModaSegundoPunto;
    private javax.swing.JButton botonOTercerPunto;
    private javax.swing.JButton botonProcesarCuartoPunto;
    private javax.swing.JButton botonTTercerPunto;
    private javax.swing.JButton botonUTercerPunto;
    private javax.swing.JButton botonVarianzaSegundoPunto;
    private javax.swing.JButton botonXTercerPunto;
    private javax.swing.JButton botonZTercerPunto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtCodigoCuartoPunto;
    private javax.swing.JTextField txtEdadCuartoPunto;
    private javax.swing.JTextField txtEntradaSegundoPunto;
    private javax.swing.JTextArea txtEntradaTercerPunto;
    private javax.swing.JTextField txtNombreCuartoPunto;
    private javax.swing.JTextField txtNumEstudiantesCuartoPunto;
    private javax.swing.JTextField txtPromedioCuartoPunto;
    private javax.swing.JTextArea txtSalidaCuartoPunto;
    private javax.swing.JTextArea txtSalidaSegundoPunto;
    private javax.swing.JTextArea txtSalidaTercerPunto;
    private javax.swing.JTextArea txtSalidaV1PrimerPunto;
    private javax.swing.JTextArea txtSalidaV2PrimerPunto;
    private javax.swing.JTextArea txtSalidaV3PrimerPunto;
    private javax.swing.JTextField txtSemestreCuartoPunto;
    private javax.swing.JTextField txtVector1PrimerPunto;
    private javax.swing.JTextField txtVector2PrimerPunto;
    // End of variables declaration//GEN-END:variables
}
